app:
  name: main_app
  host: 0.0.0.0
  port: 8888

databases:
  postgres:
    database: freeswitch_ex
    user: freeswitch
    password: freeswitch
    host: 172.17.0.3
    port: 5432
    minsize: 1
    maxsize: 5
  redis:
    db: 0
    host: 127.0.0.1
